<a href="https://colab.research.google.com/github/prajwal-tamang/5CS037/blob/main/Worksheet1_PrajwalTamang_L5CG11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import time

In [ ]:
#task1

#1
a = np.empty((2, 2))
print("1. Empty array (2x2):")
print(a)

#2
b = np.ones((4, 2))
print("\n2. Ones array (4x2):")
print(b)

#3
c = np.full((3, 3), 7)
print("\n3. Full array (3x3 filled with 7):")
print(c)

#4
x = np.array([[1, 2], [3, 4]])
d = np.zeros_like(x)
print("\n4. Zeros like x:")
print(d)

#5
e = np.ones_like(x)
print("\n5. Ones like x:")
print(e)

#6
new_list = [1, 2, 3, 4]
f = np.array(new_list)
print("\n6. Converted numpy array from list:")
print(f)

1. Empty array (2x2):
[[4.15251113e-315 0.00000000e+000]
 [6.67623510e-310 6.67623510e-310]]

2. Ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array (3x3 filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like x:
[[0 0]
 [0 0]]

5. Ones like x:
[[1 1]
 [1 1]]

6. Converted numpy array from list:
[1 2 3 4]


In [ ]:
#task2

#1
a = np.arange(10,50)
print("1. Values ranging from 10 to 49:\n",a)

#2
m = np.arange(9).reshape((3,3))
print("\n2. 3x3 matrix ranging from 0 to 8:\n",m)

#3
im = np.eye(3)
print("\n3. 3x3 identity matrix:\n",im)

#4
ra = np.random.random(30)
mean = ra.mean()
print("\n4. Mean is:\n",mean)

#5
ran = np.random.random((10,10))
ran_max = ran.max()
ran_min = ran.min()
print(f"\n5. Maximum value is:{ran_max}\nMinimum value is:{ran_min}")

#6
z = np.zeros(10, dtype="int")
z[4] = 1
print("\n6. Zero array of size 10:\n",z)

#7
arr = [1,2,0,0,4,0]
r_arr = arr[::-1]
print("\n7. Reversed array is:\n",r_arr)

#8
n = 4
border = np.ones((n, n), dtype=int)
border[1:-1, 1:-1] = 0
print("\n8. 2d array with 1 on border and 0 inside:\n",border)

#9
checker = np.zeros((3, 4), dtype=int)

for i in range(3):
    for j in range(4):
        if (i + j) % 2 == 1:
            checker[i, j] = 1

print("\n9. Checkerboard pattern:\n",checker)


1. Values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean is:
 0.35764445982702875

5. Maximum value is:0.9953624526513523
Minimum value is:0.008432397001215897

6. Zero array of size 10:
 [0 0 0 0 1 0 0 0 0 0]

7. Reversed array is:
 [0, 4, 0, 0, 2, 1]

8. 2d array with 1 on border and 0 inside:
 [[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]

9. Checkerboard pattern:
 [[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


In [ ]:
#task3
x = np.array([[1, 2],
              [3, 5]])
y = np.array([[5, 6],
              [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#1
add_xy = x + y
print("1. x + y:\n", add_xy)

#2
sub_xy = x - y
print("\n2. x - y:\n", sub_xy)

#3
mul_xy = x * 0
print("\n3. x * 0:\n", mul_xy)

#4
sq_x = x ** 2
print("\n4. Square:\n", sq_x)

#5
dot_vw = np.dot(v, w)
print("\n5. a) Dot product v.w:", dot_vw)

dot_xv = np.dot(x, v)
print("\n5. b) Dot product x.v:", dot_xv)

dot_xy = np.dot(x, y)
print("\n5. c) Dot product x.y:\n", dot_xy)

#6
con_xy = np.vstack((x, y))
print("\n6. a) Concatenate x and y:\n", con_xy)

con_vw = np.column_stack((v, w))
print("\n6. b) Concatenate v and w:\n", con_vw)

#7
try:
    con_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\n7. Error:", e)

1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 0:
 [[0 0]
 [0 0]]

4. Square:
 [[ 1  4]
 [ 9 25]]

5. a) Dot product v.w: 219

5. b) Dot product x.v: [29 77]

5. c) Dot product x.y:
 [[19 22]
 [50 58]]

6. a) Concatenate x and y:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

6. b) Concatenate v and w:
 [[ 9 11]
 [10 12]]

7. Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
#task4
import numpy as np

A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

# 1
invA = np.linalg.inv(A)
print("\n1.A * A^-1 =\n",invA)

#2
AB = A @ B
BA = B @ A
print("\n2.\nAB =\n", AB)
print("BA =\n", BA)
print("Is AB == BA? ->", np.allclose(AB, BA))

#3
lhs = (A @ B).T
rhs = B.T @ A.T
print("\n3.\n(AB)^T =\n", lhs)
print("B^T * A^T =\n", rhs)
print("Is (AB)^T = B^T A^T ? ->", np.allclose(lhs, rhs))

#Solve Linear System using Inverse Method
M = np.array([[2, -3,  1],
              [1, -1,  2],
              [3,  1, -1]])

b = np.array([-1, -3, 9])

#4
invM = np.linalg.inv(M)
X1 = invM @ b
print("\n4.Solution using inverse:")
print("X =", X1)

#5
X2 = np.linalg.solve(M, b)
print("\n5.Solution using np.linalg.solve:")
print("X =", X2)


1.A * A^-1 =
 [[-2.    1.  ]
 [ 1.75 -0.75]]

2.
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Is AB == BA? -> False

3.
(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Is (AB)^T = B^T A^T ? -> True

4.Solution using inverse:
X = [ 2.  1. -2.]

5.Solution using np.linalg.solve:
X = [ 2.  1. -2.]


In [ ]:
#4.2
#1
import time

size = 1000000

print(f"Comparing Python lists vs NumPy for element-wise multiplication")
print(f"Size: {size:,}\n")

python_list_1 = list(range(size))
python_list_2 = list(range(size))

start = time.time()
python_mult = [a * b for a, b in zip(python_list_1, python_list_2)]
python_time = time.time() - start

print(f"Python lists: {python_time:.6f} seconds")

numpy_array_1 = np.arange(size)
numpy_array_2 = np.arange(size)

start = time.time()
numpy_mult = numpy_array_1 * numpy_array_2
numpy_time = time.time() - start

print(f"NumPy arrays: {numpy_time:.6f} seconds")
print(f"\n NumPy is {python_time / numpy_time:.2f}x FASTER!")

Comparing Python lists vs NumPy for element-wise multiplication
Size: 1,000,000

Python lists: 0.137530 seconds
NumPy arrays: 0.004894 seconds

 NumPy is 28.10x FASTER!


In [ ]:
#2
size = 1000000

print(f"Comparing Python lists vs NumPy for dot product")
print(f"Size: {size:,}\n")

python_list_1 = list(range(size))
python_list_2 = list(range(size))

start = time.time()
python_dot = sum(a * b for a, b in zip(python_list_1, python_list_2))
python_time = time.time() - start

print(f"Python lists: {python_time:.6f} seconds")

numpy_array_1 = np.arange(size)
numpy_array_2 = np.arange(size)

start = time.time()
numpy_dot = np.dot(numpy_array_1, numpy_array_2)
numpy_time = time.time() - start

print(f"NumPy arrays: {numpy_time:.6f} seconds")
print(f"\n NumPy is {python_time / numpy_time:.2f}x FASTER!")

Comparing Python lists vs NumPy for dot product
Size: 1,000,000

Python lists: 0.095350 seconds
NumPy arrays: 0.001469 seconds

 NumPy is 64.90x FASTER!


In [ ]:
#3
size_matrix = 1000

print(f"Comparing Python lists vs NumPy for matrix multiplication")
print(f"Matrix size: {size_matrix}×{size_matrix}\n")

python_matrix_1 = [[i+j for j in range(size_matrix)] for i in range(size_matrix)]
python_matrix_2 = [[i+j for j in range(size_matrix)] for i in range(size_matrix)]

print("⏳ Computing Python lists (this may take a while)...")
start = time.time()
python_matmul = [[sum(python_matrix_1[i][k] * python_matrix_2[k][j]
                      for k in range(size_matrix))
                  for j in range(size_matrix)]
                 for i in range(size_matrix)]
python_time = time.time() - start

print(f"Python lists: {python_time:.6f} seconds")

numpy_matrix_1 = np.random.rand(size_matrix, size_matrix)
numpy_matrix_2 = np.random.rand(size_matrix, size_matrix)

print("⏳ Computing NumPy arrays...")
start = time.time()
numpy_matmul = np.dot(numpy_matrix_1, numpy_matrix_2)
numpy_time = time.time() - start

print(f"NumPy arrays: {numpy_time:.6f} seconds")
print(f"\n NumPy is {python_time / numpy_time:.2f}x FASTER!")
print("\n This is why NumPy is so important for data science!")

Comparing Python lists vs NumPy for matrix multiplication
Matrix size: 1000×1000

⏳ Computing Python lists (this may take a while)...
Python lists: 146.679887 seconds
⏳ Computing NumPy arrays...
NumPy arrays: 0.134929 seconds

 NumPy is 1087.09x FASTER!

 This is why NumPy is so important for data science!


In [ ]:
#4
size_matrix = 1000

print(f"Comparing Python lists vs NumPy for matrix multiplication")
print(f"Matrix size: {size_matrix}×{size_matrix}\n")

python_matrix_1 = [[i+j for j in range(size_matrix)] for i in range(size_matrix)]
python_matrix_2 = [[i+j for j in range(size_matrix)] for i in range(size_matrix)]

print("⏳ Computing Python lists (this may take a while)...")
start = time.time()
python_matmul = [[sum(python_matrix_1[i][k] * python_matrix_2[k][j]
                      for k in range(size_matrix))
                  for j in range(size_matrix)]
                 for i in range(size_matrix)]
python_time = time.time() - start

print(f"Python lists: {python_time:.6f} seconds")

numpy_matrix_1 = np.random.rand(size_matrix, size_matrix)
numpy_matrix_2 = np.random.rand(size_matrix, size_matrix)

print("⏳ Computing NumPy arrays...")
start = time.time()
numpy_matmul = np.dot(numpy_matrix_1, numpy_matrix_2)
numpy_time = time.time() - start

print(f"NumPy arrays: {numpy_time:.6f} seconds")
print(f"\n NumPy is {python_time / numpy_time:.2f}x FASTER!")
print("\n This is why NumPy is so important for data science!")

Comparing Python lists vs NumPy for matrix multiplication
Matrix size: 1000×1000

⏳ Computing Python lists (this may take a while)...
Python lists: 128.638745 seconds
⏳ Computing NumPy arrays...
NumPy arrays: 0.071995 seconds

 NumPy is 1786.76x FASTER!

 This is why NumPy is so important for data science!
